# Generated by Django 5.2.16 on 2026-07-10 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0004_demand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quantity_score', models.PositiveIntegerField(default=0)),
                ('budget_score', models.PositiveIntegerField(default=0)),
                ('distance_score', models.PositiveIntegerField(default=0)),
                ('grade_score', models.PositiveIntegerField(default=0)),
                ('organic_score', models.PositiveIntegerField(default=0)),
                ('variety_score', models.PositiveIntegerField(default=0)),
                ('date_score', models.PositiveIntegerField(default=0)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Viewed', 'Viewed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('matched_on', models.DateTimeField(auto_now_add=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='marketplace.demand')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='marketplace.produce')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('produce', 'demand')},
            },
        ),
    ]
