# Generated by Django 5.2.16 on 2026-07-10 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('quantity_available', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harvest_date', models.DateField()),
                ('shelf_life_days', models.PositiveIntegerField()),
                ('organic_certified', models.BooleanField(default=False)),
                ('grade', models.CharField(choices=[('Premium', 'Premium'), ('Grade A', 'Grade A'), ('Grade B', 'Grade B'), ('Standard', 'Standard')], default='Standard', max_length=20)),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Sold Out', 'Sold Out')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.category')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_listings', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.location')),
                ('produce_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.producetype')),
            ],
        ),
    ]
