# Generated by Django 5.2.16 on 2026-07-10 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_produce'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['county', 'town']},
        ),
        migrations.AlterModelOptions(
            name='producetype',
            options={'ordering': ['name'], 'verbose_name': 'Produce Type', 'verbose_name_plural': 'Produce Types'},
        ),
        migrations.AlterField(
            model_name='produce',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_listings', to='marketplace.category'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_listings', to='marketplace.location'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='produce_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_listings', to='marketplace.producetype'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='shelf_life_days',
            field=models.PositiveIntegerField(help_text='Enter shelf life in days.'),
        ),
    ]
