# Generated by Django 5.2.16 on 2026-07-10 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_category_options_alter_location_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('minimum_quantity', models.PositiveIntegerField()),
                ('maximum_quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('minimum_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_distance_km', models.PositiveIntegerField(default=20)),
                ('organic_required', models.BooleanField(default=False)),
                ('minimum_grade', models.CharField(choices=[('Premium', 'Premium'), ('Grade A', 'Grade A'), ('Grade B', 'Grade B'), ('Standard', 'Standard')], default='Standard', max_length=20)),
                ('needed_before', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Matched', 'Matched'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='marketplace.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='marketplace.location')),
                ('produce_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='marketplace.producetype')),
            ],
        ),
    ]
