# Generated by Django 5.2.16 on 2026-07-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_demand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produce',
            old_name='total_price',
            new_name='price_per_unit',
        ),
    ]
