# Generated by Django 5.2.16 on 2026-07-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_rename_total_price_produce_price_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('ton', 'Tonnes'), ('crate', 'Crates'), ('bag', 'Bags'), ('piece', 'Pieces'), ('litre', 'Litres')], max_length=20),
        ),
        migrations.AlterField(
            model_name='produce',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('ton', 'Tonnes'), ('crate', 'Crates'), ('bag', 'Bags'), ('piece', 'Pieces'), ('litre', 'Litres')], max_length=20),
        ),
    ]
